apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: matrix-alertmanager-receiver
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-store
    kind: ClusterSecretStore
  target:
    name: matrix-alertmanager-receiver
    creationPolicy: Owner
  data:
    - secretKey: access-token
      remoteRef:
        key: matrix-alertmanager-receiver
        property: access-token
    - secretKey: homeserver-url
      remoteRef:
        key: matrix-alertmanager-receiver
        property: homeserver-url
    - secretKey: user-id
      remoteRef:
        key: matrix-alertmanager-receiver
        property: user-id
    - secretKey: room-id
      remoteRef:
        key: matrix-alertmanager-receiver
        property: room-id
