apiVersion: v1
kind: Service
metadata:
  name: platform-status-reconciler
  namespace: platform-status-reconciler
  labels:
    app.kubernetes.io/name: platform-status-reconciler
    app.kubernetes.io/part-of: platform
spec:
  selector:
    app.kubernetes.io/name: platform-status-reconciler
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
