apiVersion: v1
kind: Service
metadata:
  name: matrix-alertmanager-receiver
  namespace: monitoring
  labels:
    app.kubernetes.io/name: matrix-alertmanager-receiver
    app.kubernetes.io/component: alerting
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: matrix-alertmanager-receiver
  ports:
    - name: http
      port: 12345
      targetPort: http
      protocol: TCP
