apiVersion: platform.integratn.tech/v1alpha1
kind: ArgoCDApplication
metadata:
  name: {{ .Name }}
  namespace: {{ .Namespace }}
  labels:
    app.kubernetes.io/name: argocd-application
    app.kubernetes.io/managed-by: kratix
    kratix.io/promise-name: {{ .WorkflowContext.PromiseName }}
    kratix.io/resource-name: {{ .Name }}
spec:
  name: vc-{{ .Name }}
  project: {{ .ProjectName }}
  destination:
    server: {{ .ArgoCDDestServer }}
    namespace: {{ .TargetNamespace }}
  source:
    repoURL: {{ .ArgoCDRepoURL }}
    chart: {{ .ArgoCDChart }}
    targetRevision: {{ .ArgoCDTargetRevision }}
    helm:
      releaseName: {{ .Name }}
      valuesObject:
        vcluster:
          image:
            tag: {{ .K8sVersion }}
        controlPlane:
          distro:
            k8s:
              enabled: true
          statefulSet:
            highAvailability:
              replicas: {{ .Replicas }}
          service:
            type: LoadBalancer
            annotations:
              io.cilium/lb-ipam-ips: {{ .VIP }}
{{- if .BackingStore }}
          backingStore:
{{ .BackingStore | toYaml | indent 12 }}
{{- end }}
          coredns:
            enabled: false
        sync:
          toHost:
            ingresses:
              enabled: true
            services:
              enabled: true
            persistentVolumeClaims:
              enabled: true
            storageClasses:
              enabled: {{ .PersistenceEnabled | toBool }}
          fromHost:
            ingressClasses:
              enabled: true
            storageClasses:
              enabled: {{ .PersistenceEnabled | toBool }}
        networking:
          replicateServices:
            fromHost:
              - from: default/kubernetes
                to: default/kubernetes
        integrations:
          externalDNS:
            enabled: {{ if .Hostname }}true{{ else }}false{{ end }}
{{ if .Hostname }}            domain: {{ .Hostname }}
{{ end }}            sync: enabled
        resources:
          requests:
            cpu: {{ .CPURequest }}
            memory: {{ .MemoryRequest }}
          limits:
            cpu: {{ .CPULimit }}
            memory: {{ .MemoryLimit }}
{{ if .PersistenceEnabled }}        persistence:
          volumeClaim:
            enabled: true
            size: {{ .PersistenceSize }}
{{ if .PersistenceClass }}            storageClass: {{ .PersistenceClass }}
{{ end }}{{ end }}        telemetry:
          disabled: true
{{ if .HelmOverrides }}{{ .HelmOverrides | toYaml | indent 8 }}
{{ end }}{{ if .ArgoCDSyncPolicy }}  syncPolicy:
{{ .ArgoCDSyncPolicy | toYaml | indent 4 }}
{{ end }}
