config:
  preserve: false
  webhookLabels:
    app.kubernetes.io/managed-by: argocd

webhooksCleanup:
  image:
    registry: docker.io
    repository: bitnami/kubectl
    tag: '1.34.1'

policyReportsCleanup:
  image:
    registry: docker.io
    repository: bitnami/kubectl
    tag: '1.34.1'

cleanupJobs:
  admissionReports:
    image:
      registry: docker.io
      repository: bitnami/kubectl
      tag: '1.34.1'
    securityContext:
      runAsNonRoot: false
      privileged: false
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
          - ALL
      seccompProfile:
        type: RuntimeDefault
  clusterAdmissionReports:
    image:
      registry: docker.io
      repository: bitnami/kubectl
      tag: '1.34.1'
    securityContext:
      runAsNonRoot: false
      privileged: false
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
          - ALL
      seccompProfile:
        type: RuntimeDefault
  ephemeralReports:
    image:
      registry: docker.io
      repository: bitnami/kubectl
      tag: '1.34.1'
    securityContext:
      runAsNonRoot: false
      privileged: false
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
          - ALL
      seccompProfile:
        type: RuntimeDefault
  clusterEphemeralReports:
    image:
      registry: docker.io
      repository: bitnami/kubectl
      tag: '1.34.1'
    securityContext:
      runAsNonRoot: false
      privileged: false
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
          - ALL
      seccompProfile:
        type: RuntimeDefault
  updateRequests:
    image:
      registry: docker.io
      repository: bitnami/kubectl
      tag: '1.34.1'
    securityContext:
      runAsNonRoot: false
      privileged: false
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
          - ALL
      seccompProfile:
        type: RuntimeDefault
