config:
  preserve: false
  webhookLabels:
    app.kubernetes.io/managed-by: argocd

webhooksCleanup:
  image:
    registry: ghcr.io
    repository: jamesatintegratnio/gitops_homelab_2_0/kubectl
    tag: 'v1.34.1'

policyReportsCleanup:
  image:
    registry: ghcr.io
    repository: jamesatintegratnio/gitops_homelab_2_0/kubectl
    tag: 'v1.34.1'

cleanupJobs:
  admissionReports:
    image:
      registry: ghcr.io
      repository: jamesatintegratnio/gitops_homelab_2_0/kubectl
      tag: 'v1.34.1'
    securityContext:
      runAsNonRoot: false
      privileged: false
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
          - ALL
      seccompProfile:
        type: RuntimeDefault
  clusterAdmissionReports:
    image:
      registry: ghcr.io
      repository: jamesatintegratnio/gitops_homelab_2_0/kubectl
      tag: 'v1.34.1'
    securityContext:
      runAsNonRoot: false
      privileged: false
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
          - ALL
      seccompProfile:
        type: RuntimeDefault
  ephemeralReports:
    image:
      registry: ghcr.io
      repository: jamesatintegratnio/gitops_homelab_2_0/kubectl
      tag: 'v1.34.1'
    securityContext:
      runAsNonRoot: false
      privileged: false
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
          - ALL
      seccompProfile:
        type: RuntimeDefault
  clusterEphemeralReports:
    image:
      registry: ghcr.io
      repository: jamesatintegratnio/gitops_homelab_2_0/kubectl
      tag: 'v1.34.1'
    securityContext:
      runAsNonRoot: false
      privileged: false
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
          - ALL
      seccompProfile:
        type: RuntimeDefault
  updateRequests:
    image:
      registry: ghcr.io
      repository: jamesatintegratnio/gitops_homelab_2_0/kubectl
      tag: 'v1.34.1'
    securityContext:
      runAsNonRoot: false
      privileged: false
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
          - ALL
      seccompProfile:
        type: RuntimeDefault

admissionController:
  serviceMonitor:
    enabled: true

backgroundController:
  serviceMonitor:
    enabled: true

cleanupController:
  serviceMonitor:
    enabled: true

reportsController:
  serviceMonitor:
    enabled: true