config:
  preserve: false
  webhookLabels:
    app.kubernetes.io/managed-by: argocd

cleanupJobs:
  admissionReports:
    image:
      registry: registry.k8s.io
      repository: kubectl
      tag: 'v1.34.1'
  clusterAdmissionReports:
    image:
      registry: registry.k8s.io
      repository: kubectl
      tag: 'v1.34.1'
  ephemeralReports:
    image:
      registry: registry.k8s.io
      repository: kubectl
      tag: 'v1.34.1'
  clusterEphemeralReports:
    image:
      registry: registry.k8s.io
      repository: kubectl
      tag: 'v1.34.1'
  updateRequests:
    image:
      registry: registry.k8s.io
      repository: kubectl
      tag: 'v1.34.1'
